version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: America/Sao_Paulo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: bull
    versions:
    - 3.20.0
    - 3.20.1
    - 3.21.0
    - 3.21.1
    - 3.22.0
    - 3.22.1
    - 3.22.3
  - dependency-name: jsoneditor
    versions:
    - 9.1.10
    - 9.1.9
    - 9.2.0
    - 9.3.0
    - 9.3.1
    - 9.4.0
  - dependency-name: express-handlebars
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: lodash
    versions:
    - 4.17.20
